export const CATEGORIES = {
  place: ["Templo", "Restaurante", "Tienda", "Museo", "Parque", "Mirador", "Actividad", "Cafetería", "Otro"],
  expense: ["Vuelos", "Transporte", "Hoteles", "Comida", "Compras", "Entradas", "Actividades", "Otros"],
  transport: ["Avión", "Shinkansen", "Tren", "Metro", "Autobús", "Bus nocturno", "Ferry", "Local"],
  task: ["Documentación", "Reservas", "Equipaje", "Dinero", "Tecnología", "Salud", "General"],
  shopping: ["Souvenirs", "Ropa", "Electrónica", "Coleccionismo", "Cosmética", "Comida", "Otro"],
};

const id = (prefix, value) => `${prefix}-${value}`;

export function createSeed() {
  return {
    version: 1,
    settings: { theme: "system", exchangeRate: 0.0058, defaultCurrency: "JPY", dayStart: "08:00", dayEnd: "22:00" },
    trips: [{
      id: "trip-japan",
      name: "Japón 2026",
      emoji: "🇯🇵",
      country: "Japón",
      startDate: "2026-10-10",
      endDate: "2026-10-24",
      travelers: 2,
      budget: 680000,
      currency: "JPY",
    }],
    activeTripId: "trip-japan",
    places: [
      {
        id: id("place", 1),
        tripId: "trip-japan",
        name: "Sensō-ji",
        city: "Tokio",
        area: "Asakusa",
        category: "Templo",
        description: "Templo budista y paseo por Nakamise-dori.",
        address: "2 Chome-3-1 Asakusa, Taito",
        lat: 35.7148,
        lng: 139.7967,
        hours: "06:00–17:00",
        estimatedPrice: 0,
        duration: 90,
        priority: "Alta",
        status: "Planeado",
        notes: "Llegar temprano para evitar multitudes.",
        link: "https://www.senso-ji.jp/",
        assignedDate: "2026-10-12",
      },
      {
        id: id("place", 2),
        tripId: "trip-japan",
        name: "Pokémon Center Shibuya",
        city: "Tokio",
        area: "Shibuya",
        category: "Tienda",
        description: "Pokémon Center dentro de Shibuya PARCO.",
        address: "6F Shibuya PARCO",
        lat: 35.662,
        lng: 139.6987,
        hours: "10:00–21:00",
        estimatedPrice: 0,
        duration: 75,
        priority: "Alta",
        status: "Planeado",
        notes: "Combinar con Nintendo Store.",
        link: "",
        assignedDate: "2026-10-13",
      },
      {
        id: id("place", 3),
        tripId: "trip-japan",
        name: "Fushimi Inari Taisha",
        city: "Kioto",
        area: "Fushimi",
        category: "Templo",
        description: "Santuario famoso por sus miles de torii.",
        address: "68 Fukakusa Yabunouchicho",
        lat: 34.9671,
        lng: 135.7727,
        hours: "24 horas",
        estimatedPrice: 0,
        duration: 150,
        priority: "Imprescindible",
        status: "Pendiente",
        notes: "Ideal al amanecer.",
        link: "",
        assignedDate: "2026-10-18",
      },
      {
        id: id("place", 4),
        tripId: "trip-japan",
        name: "teamLab Borderless",
        city: "Tokio",
        area: "Azabudai Hills",
        category: "Museo",
        description: "Museo de arte digital inmersivo.",
        address: "Azabudai Hills Garden Plaza B",
        lat: 35.6605,
        lng: 139.739,
        hours: "09:00–21:00",
        estimatedPrice: 4800,
        duration: 150,
        priority: "Alta",
        status: "Pendiente",
        notes: "Reserva obligatoria.",
        link: "https://www.teamlab.art/",
        assignedDate: "",
      },
      {
        id: id("place", 5),
        tripId: "trip-japan",
        name: "Dotonbori",
        city: "Osaka",
        area: "Namba",
        category: "Actividad",
        description: "Paseo nocturno y comida callejera.",
        address: "Dotonbori, Chuo Ward",
        lat: 34.6687,
        lng: 135.5013,
        hours: "Todo el día",
        estimatedPrice: 3000,
        duration: 120,
        priority: "Media",
        status: "Pendiente",
        notes: "Probar takoyaki.",
        link: "",
        assignedDate: "2026-10-21",
      },
    ],
    activities: [
      {
        id: id("act", 1),
        tripId: "trip-japan",
        date: "2026-10-12",
        start: "08:00",
        end: "09:00",
        title: "Desayuno en Asakusa",
        type: "Comida",
        city: "Tokio",
        placeId: "",
        location: "Asakusa",
        notes: "",
        status: "planned",
      },
      {
        id: id("act", 2),
        tripId: "trip-japan",
        date: "2026-10-12",
        start: "09:15",
        end: "10:45",
        title: "Visita a Sensō-ji",
        type: "Visita",
        city: "Tokio",
        placeId: id("place", 1),
        location: "Sensō-ji",
        notes: "",
        status: "planned",
      },
      {
        id: id("act", 3),
        tripId: "trip-japan",
        date: "2026-10-12",
        start: "11:10",
        end: "12:00",
        title: "Metro a Ueno",
        type: "Transporte",
        city: "Tokio",
        placeId: "",
        location: "Asakusa → Ueno",
        notes: "Línea Ginza",
        status: "planned",
      },
      {
        id: id("act", 4),
        tripId: "trip-japan",
        date: "2026-10-12",
        start: "12:00",
        end: "14:00",
        title: "Parque de Ueno",
        type: "Visita",
        city: "Tokio",
        placeId: "",
        location: "Ueno",
        notes: "",
        status: "planned",
      },
      {
        id: id("act", 5),
        tripId: "trip-japan",
        date: "2026-10-13",
        start: "10:00",
        end: "11:30",
        title: "Meiji Jingu",
        type: "Visita",
        city: "Tokio",
        placeId: "",
        location: "Harajuku",
        notes: "",
        status: "planned",
      },
      {
        id: id("act", 6),
        tripId: "trip-japan",
        date: "2026-10-13",
        start: "16:00",
        end: "17:15",
        title: "Pokémon Center Shibuya",
        type: "Compras",
        city: "Tokio",
        placeId: id("place", 2),
        location: "Shibuya PARCO",
        notes: "",
        status: "planned",
      },
    ],
    tasks: [
      {
        id: id("task", 1),
        tripId: "trip-japan",
        title: "Reservar Museo Ghibli",
        phase: "Antes",
        category: "Reservas",
        priority: "Alta",
        dueDate: "2026-09-10",
        status: "Pendiente",
        notes: "Entradas salen un mes antes.",
      },
      {
        id: id("task", 2),
        tripId: "trip-japan",
        title: "Comprar eSIM",
        phase: "Antes",
        category: "Tecnología",
        priority: "Media",
        dueDate: "2026-10-05",
        status: "Pendiente",
        notes: "Comparar cobertura.",
      },
      {
        id: id("task", 3),
        tripId: "trip-japan",
        title: "Descargar mapas offline",
        phase: "Antes",
        category: "Tecnología",
        priority: "Media",
        dueDate: "2026-10-08",
        status: "Pendiente",
        notes: "Tokio, Kioto y Osaka.",
      },
      {
        id: id("task", 4),
        tripId: "trip-japan",
        title: "Activar JR tickets",
        phase: "Durante",
        category: "Documentación",
        priority: "Alta",
        dueDate: "2026-10-11",
        status: "Pendiente",
        notes: "",
      },
    ],
    purchases: [
      {
        id: id("buy", 1),
        tripId: "trip-japan",
        product: "Peluche exclusivo Pikachu",
        category: "Coleccionismo",
        recipient: "Yo",
        city: "Tokio",
        store: "Pokémon Center Shibuya",
        estimatedPrice: 4800,
        maxBudget: 6000,
        priority: "Alta",
        status: "Pendiente",
        actualPrice: 0,
        purchaseDate: "",
        notes: "Edición local si existe.",
      },
      {
        id: id("buy", 2),
        tripId: "trip-japan",
        product: "Cuchillo santoku",
        category: "Hogar",
        recipient: "Casa",
        city: "Kioto",
        store: "Aritsugu",
        estimatedPrice: 18000,
        maxBudget: 25000,
        priority: "Media",
        status: "Pendiente",
        actualPrice: 0,
        purchaseDate: "",
        notes: "Comprobar equipaje facturado.",
      },
      {
        id: id("buy", 3),
        tripId: "trip-japan",
        product: "KitKat regionales",
        category: "Comida",
        recipient: "Familia",
        city: "Osaka",
        store: "Don Quijote",
        estimatedPrice: 3000,
        maxBudget: 4000,
        priority: "Baja",
        status: "Pendiente",
        actualPrice: 0,
        purchaseDate: "",
        notes: "",
      },
    ],
    expenses: [
      {
        id: id("exp", 1),
        tripId: "trip-japan",
        title: "Vuelos ida y vuelta",
        category: "Vuelos",
        city: "Tokio",
        date: "2026-10-10",
        estimatedAmount: 240000,
        actualAmount: 226000,
        currency: "JPY",
        paymentStatus: "Pagado",
        person: "Ambos",
        notes: "",
      },
      {
        id: id("exp", 2),
        tripId: "trip-japan",
        title: "Hoteles Tokio",
        category: "Hoteles",
        city: "Tokio",
        date: "2026-10-11",
        estimatedAmount: 140000,
        actualAmount: 70000,
        currency: "JPY",
        paymentStatus: "Parcial",
        person: "Ambos",
        notes: "50% pagado",
      },
      {
        id: id("exp", 3),
        tripId: "trip-japan",
        title: "Hotel Kioto",
        category: "Hoteles",
        city: "Kioto",
        date: "2026-10-17",
        estimatedAmount: 85000,
        actualAmount: 0,
        currency: "JPY",
        paymentStatus: "Pendiente",
        person: "Ambos",
        notes: "",
      },
      {
        id: id("exp", 4),
        tripId: "trip-japan",
        title: "Shinkansen Tokio–Kioto",
        category: "Transporte",
        city: "Tokio",
        date: "2026-10-17",
        estimatedAmount: 28000,
        actualAmount: 0,
        currency: "JPY",
        paymentStatus: "Pendiente",
        person: "Ambos",
        notes: "",
      },
      {
        id: id("exp", 5),
        tripId: "trip-japan",
        title: "Entradas teamLab",
        category: "Entradas",
        city: "Tokio",
        date: "2026-10-15",
        estimatedAmount: 9600,
        actualAmount: 9600,
        currency: "JPY",
        paymentStatus: "Pagado",
        person: "Ambos",
        notes: "",
      },
    ],
    stays: [{
      id: id("stay", 1),
      tripId: "trip-japan",
      name: "The Gate Hotel Kaminarimon",
      city: "Tokio",
      address: "2-16-11 Kaminarimon, Taito",
      lat: 35.7101,
      lng: 139.7957,
      checkInDate: "2026-10-11",
      checkOutDate: "2026-10-17",
      checkInTime: "15:00",
      checkOutTime: "11:00",
      price: 140000,
      paymentStatus: "Parcial",
      reference: "JP26-GATE-184",
      link: "",
      contact: "+81 3 5826 3877",
      notes: "Habitación no fumadores",
    }],
    transports: [{
      id: id("trans", 1),
      tripId: "trip-japan",
      type: "Avión",
      operator: "Iberia",
      origin: "Madrid MAD",
      destination: "Tokio NRT",
      departureDate: "2026-10-10",
      departureTime: "12:30",
      arrivalDate: "2026-10-11",
      arrivalTime: "10:10",
      duration: 940,
      price: 226000,
      reservation: "IB-JP26-X7K",
      seat: "24A / 24B",
      link: "",
      notes: "Terminal 4S",
      status: "Confirmado",
    }, {
      id: id("trans", 2),
      tripId: "trip-japan",
      type: "Shinkansen",
      operator: "JR Central",
      origin: "Tokyo Station",
      destination: "Kyoto Station",
      departureDate: "2026-10-17",
      departureTime: "09:03",
      arrivalDate: "2026-10-17",
      arrivalTime: "11:15",
      duration: 132,
      price: 28000,
      reservation: "",
      seat: "Pendiente",
      link: "",
      notes: "Nozomi",
      status: "Por reservar",
    }],
    reservations: [{
      id: id("res", 1),
      tripId: "trip-japan",
      title: "teamLab Borderless",
      type: "Museo",
      date: "2026-10-15",
      time: "10:00",
      reference: "TLB-261015",
      paymentStatus: "Pagado",
      status: "Confirmada",
      link: "",
      notes: "Llegar 15 minutos antes",
    }],
    documents: [{
      id: id("doc", 1),
      tripId: "trip-japan",
      name: "Seguro de viaje",
      type: "Seguro",
      reference: "POL-JP-2026",
      link: "",
      expiryDate: "2026-10-25",
      notes: "Cobertura médica y cancelación",
    }],
  };
}
